### PR TITLE
fix: CodeQL warnings

### LINKED ISSUE #1826: [BUG] Fix CodeQL warnings
### Description

Currently, there are many CodeQL warnings. LGTM is marking our code quality as `B`. We need to get it higher (link: https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/alerts/?mode=list).

### Expected behavior

We should fix all the CodeQL/LGTM warnings.

### Actual behavior

LGTM is reporting 7 alerts, which marks our quality code as `B`.

### Possible fix

Fix all the CodeQL/LGTM warnings.

### Steps to reproduce

1. Go to https://lgtm.com/projects/g/TheAlgorithms/C-Plus-Plus/alerts/?mode=list.
2. You will see all the warnings CodeQL is reporting, which makes it easier for us to fix them.
3. There's a help button in case you need help or are confused with that error.

### Context

Having bugs in our code (even minimal bugs) can make it all go wrong or simply affect other students/people reading and understanding our algorithms.

### Additional information

Nope.

### PR DESCRIPTION
**Pull request by 2kindsofcs**
#### Description of Change

Fix #1826.

in order to remove warnings related to `reverse_a_linked_list.cpp`, I added `return 0`. 

by the way, I think `data_structures/reverse_a_linked_list.cpp` could be improved. 
for example, [catch statement in list::top](https://github.com/2kindsofcs/C-Plus-Plus/blob/master/data_structures/reverse_a_linked_list.cpp#L128) will not be executed when the list is empty.  

#### Checklist

- [x] Added description of change
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
added return statements and removed unnecessary comparison in functions. 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C-Plus-Plus/pull/1827"></a>

### CODE REVIEW

File: data_structures/reverse_a_linked_list.cpp [hunk 1]
```diff
@@ -165,6 +167,7 @@ int32_t list::traverse(int index) {
     /* if we get to this line,the caller was asking for a non-existent element
     so we assert fail */
     assert(0);
```
Comment (Panquesito7) [inline data_structures/reverse_a_linked_list.cpp:169]: According to the comments, we might want to use `exit(1)` instead, to quit the program successfully.

**Review by Panquesito7 — DISMISSED** [review]
LGTM 🚀 Thank you for your contribution! 😄👍

**Review by amino19 — APPROVED** [review]

**Review by ayaankhan98 — DISMISSED** [review]
RSLGTM!

**Review by Panquesito7 — APPROVED** [review]
