### PR TITLE
fix: add cstdint header to all files using fixed width integers

### LINKED ISSUE #2710: [BUG] gcc >= 13 reordered headers.
### Description

#2702 mentions reports of algorithms failing to compile due to a reordering of the headerfiles. Including cstdint would be better practice too.

### Expected behavior

all typedefs of primitive types containing files compiles

### Actual behavior

Compilation failure

### Steps to reproduce

1. Use gcc >= 13
2. Run cmake build on any of the algorithm containing typedefs like uint8_t

### Context

Requiring temporary inclusions of cstdint before creating changes then removing them for the actual pr

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by realstealthninja**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: fixes #2710

### CODE REVIEW

**Comment by realstealthninja** [comment]
I understand one big pr is frowned upon but opening 81 seperate prs seems very unnecessary.
the files you see with large diffs are mostly linting done by the ide so it fits clang tidy

File: sorting/selection_sort_recursive.cpp [hunk 1]
```diff
@@ -28,9 +28,10 @@
  */
 
 #include <algorithm>  /// for std::is_sorted
-#include <cassert>    /// for assert
-#include <iostream>   /// for std::swap and io operations
-#include <vector>     /// for std::vector
+#include <cassert>  /// for assert#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/selection_sort_recursive.cpp:31]:
```suggestion
#include <cassert>  /// for assert
```

**Comment by realstealthninja** [comment]
Should we use `For std::uint32_t` or integral typedefs leaning towards the former at the moment.

File: backtracking/subarray_sum.cpp [hunk 2]
```diff
@@ -14,6 +14,7 @@
  */
 
 #include <cassert>        /// for assert
+#include <cstdint>        /// for integral typedefs
```
Comment (vil02) [inline backtracking/subarray_sum.cpp:17]: The comment is not too useful. It could well be something like
```suggestion
#include <cstdint>        /// included because it is needed
```
I would suggest, in case of this file, to
```suggestion
#include <cstdint>        /// for int_64_t and uint64_t
```
I realize that it might be hard to do it by hand. [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use) might help to automate this process.

On the other hand: I am not sure if these comments are needed at all. Having in mind that this change is very urgent (79 files do not compile), I would just skip the comments.

By the way: these types are called [_fixed width integer types_](https://en.cppreference.com/w/cpp/types/integer).

Comment (realstealthninja) [reply backtracking/subarray_sum.cpp:17]: > The comment is not too useful. It could well be something like
> ```suggestion
> #include <cstdint>        /// included because it is needed

Yes I do agree

> ```
> I would suggest, in case of this file, to
> ```suggestion
> #include <cstdint>        /// for int_64_t and uint64_t

We'd have to look through the entire file
But in general is probably just uint64_t

> ```
> I realize that it might be hard to do it by hand. [include-what-you-use](https://github.com/include-what-you-use/include-what-you-use) might help to automate this process.

I'll have a look into this. Does this provide this type of comment or
A different style?

> On the other hand: I am not sure if these comments are needed at all. Having in mind that this change is very urgent (79 files do not compile), I would just skip the comments.

Oversight on my part. Some of the files listed does not have comments on the other includes. But on the other hand, not including them would contribute to 
#2546


> By the way: these types are called [_fixed width integer types_](https://en.cppreference.com/w/cpp/types/integer).

Oh thanks for letting me know 🙂

Comment (vil02) [reply backtracking/subarray_sum.cpp:17]: > I'll have a look into this. Does this provide this type of comment or A different style?

The _full_ output of for this file looks like that:
```
#include <cassert>        // for assert
#include <cstdint>        // for int64_t, uint64_t
#include <iostream>       // for operator<<, cout, endl, ostream, basic_ostream
#include <unordered_map>  // for unordered_map, operator!=, unordered_map<>::iterator, _Node_iterator_base
#include <vector>         // for vector
```

Skipping one of the `/` might be actually a good idea, cf. #2493.

File: math/fibonacci_matrix_exponentiation.cpp [hunk 3]
```diff
@@ -1,113 +1,116 @@
...
+           mod;
 }
 
 /**
  * Function to test above algorithm
  */
-void test()
-{
-    assert(fibo(6, 1000000007 ) == 8);
+void test() {
```
Comment (Panquesito7) [inline math/fibonacci_matrix_exponentiation.cpp:91]:
```suggestion
static void test() {
```

File: math/sieve_of_eratosthenes.cpp [hunk 4]
```diff
@@ -54,9 +57,11 @@ void print(uint32_t N, const std::vector<bool> &is_prime) {
  * Test implementations
  */
 void tests() {
```
Comment (Panquesito7) [inline math/sieve_of_eratosthenes.cpp:59]:
```suggestion
static void tests() {
```

**Review by Panquesito7 — COMMENTED** [review]
Overall, everything looks good. Thanks!

**Comment by realstealthninja** [comment]
Going to stick with integral typedefs since iwyu doesnt seem to work for me. We can implement that as a later pr. For now the most important thing is to fix the compilation issue, documentation can wait

**Review by vil02 — APPROVED** [review]
As I mentioned earlier: I would suggest to remove the `/// for integral typedefs` part.

**Comment by realstealthninja** [comment]
Oh yes forgot that thanks for reminding me

File: ciphers/base64_encoding.cpp [hunk 5]
```diff
@@ -13,6 +13,7 @@
  */
 #include <array>     /// for `std::array`
 #include <cassert>   /// for `assert` operations
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline ciphers/base64_encoding.cpp:16]:
```suggestion
#include <cstdint>
```

File: ciphers/hill_cipher.cpp [hunk 6]
```diff
@@ -35,6 +35,7 @@
 
 #include <cassert>
 #include <cmath>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline ciphers/hill_cipher.cpp:38]:
```suggestion
#include <cstdint>
```

File: ciphers/uint128_t.hpp [hunk 7]
```diff
@@ -8,6 +8,7 @@
  */
 
 #include <algorithm>  /// for `std::reverse` and other operations
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline ciphers/uint128_t.hpp:11]:
```suggestion
#include <cstdint>
```

File: cpu_scheduling_algorithms/fcfs_scheduling.cpp [hunk 8]
```diff
@@ -11,6 +11,7 @@
 
 #include <algorithm>      /// for sorting
 #include <cassert>        /// for assert
+#include <cstdint>        /// for integral typedefs
```
Comment (realstealthninja) [inline cpu_scheduling_algorithms/fcfs_scheduling.cpp:14]:
```suggestion
#include <cstdint>
```

File: data_structures/dsu_path_compression.cpp [hunk 9]
```diff
@@ -19,6 +19,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline data_structures/dsu_path_compression.cpp:22]:
```suggestion
#include <cstdint>
```

File: data_structures/dsu_union_rank.cpp [hunk 10]
```diff
@@ -20,6 +20,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline data_structures/dsu_union_rank.cpp:23]:
```suggestion
#include <cstdint>
```

File: data_structures/list_array.cpp [hunk 11]
```diff
@@ -4,17 +4,20 @@
...
+ * You can insert element, sort them in order, search efficiently, delete values
+ * and print the list.
  */
 
-#include <iostream> /// for io operations
-#include <array>   /// for std::array
-#include <cassert> /// for assert
+#include <array>     /// for std::array
+#include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline data_structures/list_array.cpp:19]:
```suggestion
#include <cstdint>
```

File: data_structures/queue_using_array.cpp [hunk 12]
```diff
@@ -18,6 +18,7 @@
  * @author [Farbod Ahmadian](https://github.com/farbodahm)
  */
 #include <array>     /// for std::array
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline data_structures/queue_using_array.cpp:21]:
```suggestion
#include <cstdint>
```

File: data_structures/sparse_table.cpp [hunk 13]
```diff
@@ -24,6 +24,7 @@
 
 #include <array>     /// for std::array
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline data_structures/sparse_table.cpp:27]:
```suggestion
#include <cstdint>
```

File: data_structures/stack_using_queue.cpp [hunk 14]
```diff
@@ -9,6 +9,7 @@
  * @author [tushar2407](https://github.com/tushar2407)
  */
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline data_structures/stack_using_queue.cpp:12]:
```suggestion
#include <cstdint>
```

File: data_structures/treap.cpp [hunk 15]
```diff
@@ -19,6 +19,7 @@
 
 #include <array>     /// For array
 #include <cassert>   /// For assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline data_structures/treap.cpp:22]:
```suggestion
#include <cstdint>
```

File: geometry/graham_scan_functions.hpp [hunk 16]
```diff
@@ -39,6 +39,7 @@
  *
  *******************************************************************************/
 #include <algorithm>  /// for std::swap
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline geometry/graham_scan_functions.hpp:42]:
```suggestion
#include <cstdint>
```

File: graph/bidirectional_dijkstra.cpp [hunk 17]
```diff
@@ -14,6 +14,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline graph/bidirectional_dijkstra.cpp:17]:
```suggestion
#include <cstdint>
```

File: graph/connected_components_with_dsu.cpp [hunk 18]
```diff
@@ -3,20 +3,24 @@
...
+ * 1st option is inefficient, Disjoint union is the most optimal way to find
+ * this.
  *
  * @author Unknown author
  * @author [Sagar Pandya](https://github.com/sagarpandyansit)
  */
-#include <iostream> /// for IO operations
-#include <set>    /// for std::set
-#include <vector> /// for std::vector
+#include <cstdint>   /// for integer typedefs
```
Comment (realstealthninja) [inline graph/connected_components_with_dsu.cpp:20]:
```suggestion
#include <cstdint>
```

File: graph/cycle_check_directed_graph.cpp [hunk 19]
```diff
@@ -7,6 +7,7 @@
  *
  */
 
+#include <cstdint>      /// for integral typedefs
```
Comment (realstealthninja) [inline graph/cycle_check_directed_graph.cpp:10]:
```suggestion
#include <cstdint>
```

File: graph/is_graph_bipartite2.cpp [hunk 20]
```diff
@@ -15,6 +15,7 @@
  * @author [tushar2407](https://github.com/tushar2407)
  */
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline graph/is_graph_bipartite2.cpp:18]:
```suggestion
#include <cstdint>
```

File: graph/travelling_salesman_problem.cpp [hunk 21]
```diff
@@ -19,6 +19,7 @@
 
 #include <algorithm>  /// for std::min
 #include <cassert>    /// for assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline graph/travelling_salesman_problem.cpp:22]:
```suggestion
#include <cstdint>
```

File: hashing/md5.cpp [hunk 22]
```diff
@@ -41,6 +41,7 @@
 #include <algorithm>  /// Used for std::copy
 #include <array>      /// Used for std::array
 #include <cassert>    /// Used for assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline hashing/md5.cpp:44]:
```suggestion
#include <cstdint>
```

File: hashing/sha1.cpp [hunk 23]
```diff
@@ -32,6 +32,7 @@
 #include <algorithm>  /// For std::copy
 #include <array>      /// For std::array
 #include <cassert>    /// For assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline hashing/sha1.cpp:35]:
```suggestion
#include <cstdint>
```

File: math/n_choose_r.cpp [hunk 24]
```diff
@@ -11,8 +11,8 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/n_choose_r.cpp:14]:
```suggestion
#include <cstdint>
```

File: strings/z_function.cpp [hunk 25]
```diff
@@ -11,6 +11,7 @@
  * @author [Ritika Gupta](https://github.com/RitikaGupta8734)
  */
 
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline strings/z_function.cpp:14]:
```suggestion
#include <cstdint>
```

File: strings/manacher_algorithm.cpp [hunk 26]
```diff
@@ -11,6 +11,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline strings/manacher_algorithm.cpp:14]:
```suggestion
#include <cstdint>
```

File: sorting/wiggle_sort.cpp [hunk 27]
```diff
@@ -19,6 +19,7 @@
 
 #include <algorithm>
 #include <cassert>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/wiggle_sort.cpp:22]:
```suggestion
#include <cstdint>
```

File: sorting/selection_sort_recursive.cpp [hunk 28]
```diff
@@ -28,9 +28,10 @@
  */
 
 #include <algorithm>  /// for std::is_sorted
-#include <cassert>    /// for assert
-#include <iostream>   /// for std::swap and io operations
-#include <vector>     /// for std::vector
+#include <cassert>  /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/selection_sort_recursive.cpp:32]:
```suggestion
#include <cstdint>
```

File: sorting/selection_sort_iterative.cpp [hunk 29]
```diff
@@ -29,6 +29,7 @@
  *******************************************************************************/
 #include <algorithm>  /// for std::is_sorted
 #include <cassert>    /// for std::assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/selection_sort_iterative.cpp:32]:
```suggestion
#include <cstdint>
```

File: sorting/recursive_bubble_sort.cpp [hunk 30]
```diff
@@ -43,16 +50,19 @@
...
 
-#include <cassert>   /// for assert
-#include <iostream>  /// for IO operations
-#include <vector>    /// for std::vector
-#include <array>     /// for std::array
-#include <algorithm> /// for std::is_sorted
+#include <algorithm>  /// for std::is_sorted
+#include <array>      /// for std::array
+#include <cassert>    /// for assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/recursive_bubble_sort.cpp:63]:
```suggestion
#include <cstdint>
```

File: sorting/radix_sort2.cpp [hunk 31]
```diff
@@ -23,8 +23,10 @@
  */
 
 /// header files
+
 #include <algorithm>  /// for collection of functions
 #include <cassert>  /// for a macro called assert which can be used to verify assumptions
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/radix_sort2.cpp:29]:
```suggestion
#include <cstdint>
```

File: sorting/dnf_sort.cpp [hunk 32]
```diff
@@ -12,6 +12,7 @@
 
 #include <algorithm>  /// for std::is_sorted
 #include <cassert>    /// for assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/dnf_sort.cpp:15]:
```suggestion
#include <cstdint>
```

File: sorting/cycle_sort.cpp [hunk 33]
```diff
@@ -13,6 +13,7 @@
 
 #include <algorithm>  /// for std::is_sorted, std::swap
 #include <cassert>    /// for assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/cycle_sort.cpp:16]:
```suggestion
#include <cstdint>
```

File: search/sublist_search.cpp [hunk 34]
```diff
@@ -26,6 +26,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline search/sublist_search.cpp:29]:
```suggestion
#include <cstdint>
```

File: search/saddleback_search.cpp [hunk 35]
```diff
@@ -1,45 +1,52 @@
...
+ * array. Also, each row and column of the matrix should be sorted beforehand
+ * for this algorithm to work.
  *
  * @author [Hashir Niazi](https://github.com/HashirGJ8842)
  */
-#include <cassert>      /// for assert
-#include <iostream>     /// for io operations, and std::pair
-#include <vector>       /// for std::vector
+#include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline search/saddleback_search.cpp:16]:
```suggestion
#include <cstdint>
```

File: search/interpolation_search.cpp [hunk 36]
```diff
@@ -31,6 +31,7 @@
 
 #include <algorithm>  /// for std::sort function
 #include <cassert>    /// for std::assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline search/interpolation_search.cpp:34]:
```suggestion
#include <cstdint>
```

File: search/floyd_cycle_detection_algo.cpp [hunk 37]
```diff
@@ -12,9 +12,9 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline search/floyd_cycle_detection_algo.cpp:15]:
```suggestion
#include <cstdint>
```

File: search/exponential_search.cpp [hunk 38]
```diff
@@ -14,7 +14,8 @@
  */
 #include <cassert>
 #include <cmath>
-#include <iostream>
+#include <cstdint>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline search/exponential_search.cpp:18]:
```suggestion
#include <cstdint>
```

File: search/exponential_search.cpp [hunk 39]
```diff
@@ -14,7 +14,8 @@
  */
 #include <cassert>
 #include <cmath>
-#include <iostream>
+#include <cstdint>
```
Comment (realstealthninja) [inline search/exponential_search.cpp:17]:
```suggestion
```

File: search/binary_search.cpp [hunk 40]
```diff
@@ -36,6 +36,7 @@
 
 #include <algorithm>  /// for std::sort function
 #include <cassert>    /// for std::assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline search/binary_search.cpp:39]:
```suggestion
#include <cstdint>
```

File: others/lru_cache.cpp [hunk 41]
```diff
@@ -46,6 +46,7 @@
  * */
 
 #include <cassert>        /// for assert
+#include <cstdint>        /// for integral typedefs
```
Comment (realstealthninja) [inline others/lru_cache.cpp:49]:
```suggestion
#include <cstdint>
```

File: search/binary_search.cpp (hunk 40 above)
Comment (realstealthninja) [inline search/binary_search.cpp:39]:
```suggestion
#include <cstdint>
```

File: math/n_bonacci.cpp [hunk 42]
```diff
@@ -16,9 +16,9 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/n_bonacci.cpp:19]:
```suggestion
#include <cstdint>
```

File: math/aliquot_sum.cpp [hunk 43]
```diff
@@ -20,6 +20,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/aliquot_sum.cpp:23]:
```suggestion
#include <cstdint>
```

Comment (realstealthninja) [inline math/aliquot_sum.cpp:23]:
```suggestion
#include <cstdint>
```

File: math/check_factorial.cpp [hunk 44]
```diff
@@ -10,6 +10,7 @@
  * @author [ewd00010](https://github.com/ewd00010)
  */
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/check_factorial.cpp:13]:
```suggestion
#include <cstdint>
```

File: math/double_factorial.cpp [hunk 45]
```diff
@@ -10,6 +10,7 @@
  */
 
 #include <cassert>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline math/double_factorial.cpp:13]:
```suggestion
#include <cstdint>
```

File: math/eulers_totient_function.cpp [hunk 46]
```diff
@@ -24,8 +25,9 @@
  * @author [Mann Mehta](https://github.com/mann2108)
  */
 
-#include <iostream> /// for IO operations
-#include <cassert> /// for assert
+#include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/eulers_totient_function.cpp:29]:
```suggestion
#include <cstdint>
```

File: math/factorial.cpp [hunk 47]
```diff
@@ -12,8 +12,8 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/factorial.cpp:15]:
```suggestion
#include <cstdint>
```

File: math/fibonacci.cpp [hunk 48]
```diff
@@ -9,8 +9,8 @@
  * @see fibonacci_large.cpp, fibonacci_fast.cpp, string_fibonacci.cpp
  */
 #include <cassert>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline math/fibonacci.cpp:12]:
```suggestion
#include <cstdint>
```

File: math/fibonacci_matrix_exponentiation.cpp [hunk 49]
```diff
@@ -1,113 +1,116 @@
...
  * \author [unknown author]()
- * @see fibonacci.cpp, fibonacci_fast.cpp, string_fibonacci.cpp, fibonacci_large.cpp
+ * @see fibonacci.cpp, fibonacci_fast.cpp, string_fibonacci.cpp,
+ * fibonacci_large.cpp
  */
 
-#include<iostream>
-#include<vector>
 #include <cassert>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline math/fibonacci_matrix_exponentiation.cpp:16]:
```suggestion
#include <cstdint>
```

File: math/fibonacci_sum.cpp [hunk 50]
```diff
@@ -13,6 +13,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/fibonacci_sum.cpp:16]:
```suggestion
#include <cstdint>
```

File: math/finding_number_of_digits_in_a_number.cpp [hunk 51]
```diff
@@ -18,6 +18,7 @@
 
 #include <cassert>   /// for assert
 #include <cmath>     /// for log calculation
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/finding_number_of_digits_in_a_number.cpp:21]:
```suggestion
#include <cstdint>
```

File: math/integral_approximation.cpp [hunk 52]
```diff
@@ -1,18 +1,29 @@
...
+ * smaller and smaller, the sum approaches the Riemann integral. \author
+ * [Benjamin Walton](https://github.com/bwalton24) \author [Shiqi
+ * Sheng](https://github.com/shiqisheng00)
  */
-#include <cassert>        /// for assert
-#include <cmath>         /// for mathematical functions
-#include <functional>   /// for passing in functions
+#include <cassert>     /// for assert
+#include <cmath>       /// for mathematical functions
+#include <cstdint>     /// for integral typedefs
```
Comment (realstealthninja) [inline math/integral_approximation.cpp:25]:
```suggestion
#include <cstdint>
```

File: math/inv_sqrt.cpp [hunk 53]
```diff
@@ -10,9 +10,9 @@
 
 #include <cassert>   /// for assert
 #include <cmath>     /// for `std::sqrt`
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/inv_sqrt.cpp:13]:
```suggestion
#include <cstdint>
```

File: math/largest_power.cpp [hunk 54]
```diff
@@ -1,78 +1,77 @@
...
+ * @see more on
+ * https://math.stackexchange.com/questions/141196/highest-power-of-a-prime-p-dividing-n
  * @author [uday6670](https://github.com/uday6670)
  */
 
-#include <iostream> /// for std::cin and std::cout
-#include <cassert>  /// for assert
-
+#include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/largest_power.cpp:15]:
```suggestion
#include <cstdint>
```

File: math/lcm_sum.cpp [hunk 55]
```diff
@@ -13,6 +13,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/lcm_sum.cpp:16]:
```suggestion
#include <cstdint>
```

File: sorting/quick_sort.cpp [hunk 56]
```diff
@@ -26,6 +26,7 @@
 
 #include <algorithm>  /// for std::is_sorted
 #include <cassert>    /// for std::assert
+#include <cstdint>    /// for integral typedefs
```
Comment (realstealthninja) [inline sorting/quick_sort.cpp:29]:
```suggestion
#include <cstdint>
```

File: others/kadanes3.cpp [hunk 57]
```diff
@@ -17,8 +17,8 @@
 #include <array>     /// for std::array
 #include <cassert>   /// for assert
 #include <climits>   /// for INT_MIN value
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline others/kadanes3.cpp:20]:
```suggestion
#include <cstdint>
```

File: others/easter.cpp [hunk 58]
```diff
@@ -18,6 +18,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline others/easter.cpp:21]:
```suggestion
#include <cstdint>
```

File: numerical_methods/rungekutta.cpp [hunk 59]
```diff
@@ -19,9 +19,9 @@
  * There can be many such equations
  */
 #include <cassert>   /// asserting the test functions
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline numerical_methods/rungekutta.cpp:22]:
```suggestion
#include <cstdint>
```

File: numerical_methods/newton_raphson_method.cpp [hunk 60]
```diff
@@ -13,6 +13,7 @@
  * \see bisection_method.cpp, false_position.cpp
  */
 #include <cmath>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline numerical_methods/newton_raphson_method.cpp:16]:
```suggestion
#include <cstdint>
```

File: numerical_methods/inverse_fast_fourier_transform.cpp [hunk 61]
```diff
@@ -14,6 +14,7 @@
 #include <cassert>   /// for assert
 #include <cmath>     /// for mathematical-related functions
 #include <complex>   /// for storing points and coefficents
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline numerical_methods/inverse_fast_fourier_transform.cpp:17]:
```suggestion
#include <cstdint>
```

File: numerical_methods/golden_search_extrema.cpp [hunk 62]
```diff
@@ -10,6 +10,7 @@
 #define _USE_MATH_DEFINES  //< required for MS Visual C++
 #include <cassert>
 #include <cmath>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline numerical_methods/golden_search_extrema.cpp:13]:
```suggestion
#include <cstdint>
```

File: numerical_methods/fast_fourier_transform.cpp [hunk 63]
```diff
@@ -22,6 +22,7 @@
 #include <cassert>   /// for assert
 #include <cmath>     /// for mathematical-related functions
 #include <complex>   /// for storing points and coefficents
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline numerical_methods/fast_fourier_transform.cpp:25]:
```suggestion
#include <cstdint>
```

Comment (realstealthninja) [inline numerical_methods/fast_fourier_transform.cpp:25]:
```suggestion
#include <cstdint>
```

File: numerical_methods/durand_kerner_roots.cpp [hunk 64]
```diff
@@ -33,6 +33,7 @@
 #include <cassert>
 #include <cmath>
 #include <complex>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline numerical_methods/durand_kerner_roots.cpp:36]:
```suggestion
#include <cstdint>
```

File: numerical_methods/brent_method_extrema.cpp [hunk 65]
```diff
@@ -16,6 +16,7 @@
 #define _USE_MATH_DEFINES  ///< required for MS Visual C++
 #include <cassert>
 #include <cmath>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline numerical_methods/brent_method_extrema.cpp:19]:
```suggestion
#include <cstdint>
```

File: math/sum_of_binomial_coefficient.cpp [hunk 66]
```diff
@@ -10,6 +10,7 @@
  * @author [muskan0719](https://github.com/muskan0719)
  */
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/sum_of_binomial_coefficient.cpp:13]:
```suggestion
#include <cstdint>
```

File: math/string_fibonacci.cpp [hunk 67]
```diff
@@ -8,6 +8,7 @@
  * @see fibonacci_large.cpp, fibonacci_fast.cpp, fibonacci.cpp
  */
 
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline math/string_fibonacci.cpp:11]:
```suggestion
#include <cstdint>
```

File: math/sieve_of_eratosthenes.cpp [hunk 68]
```diff
@@ -12,6 +12,7 @@
  */
 
 #include <cassert>
+#include <cstdint>  /// for integral typedefs
```
Comment (realstealthninja) [inline math/sieve_of_eratosthenes.cpp:15]:
```suggestion
#include <cstdint>
```

File: math/n_bonacci.cpp (hunk 42 above)
Comment (realstealthninja) [inline math/n_bonacci.cpp:19]:
```suggestion
#include <cstdint>
```

File: math/modular_inverse_simple.cpp [hunk 69]
```diff
@@ -8,6 +8,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/modular_inverse_simple.cpp:11]:
```suggestion
#include <cstdint>
```

File: math/modular_exponentiation.cpp [hunk 70]
```diff
@@ -17,8 +17,8 @@
  * @author [Shri2206](https://github.com/Shri2206)
  */
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/modular_exponentiation.cpp:20]:
```suggestion
#include <cstdint>
```

File: math/magic_number.cpp [hunk 71]
```diff
@@ -17,6 +17,7 @@
  * @author [Neha Hasija](https://github.com/neha-hasija17)
  */
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/magic_number.cpp:20]:
```suggestion
#include <cstdint>
```

File: math/linear_recurrence_matrix.cpp [hunk 72]
```diff
@@ -18,6 +18,7 @@
  * @author [Ashish Daulatabad](https://github.com/AshishYUO)
  */
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/linear_recurrence_matrix.cpp:21]:
```suggestion
#include <cstdint>
```

File: math/lcm_sum.cpp (hunk 55 above)
Comment (realstealthninja) [inline math/lcm_sum.cpp:16]:
```suggestion
#include <cstdint>
```

File: math/largest_power.cpp (hunk 54 above)
Comment (realstealthninja) [inline math/largest_power.cpp:15]:
```suggestion
#include <cstdint>
```

**Review by vil02 — APPROVED** [review]

File: math/modular_division.cpp [hunk 73]
```diff
@@ -25,6 +25,7 @@
  */
 
 #include <cassert>   /// for assert
+#include <cstdint>   /// for integral typedefs
```
Comment (realstealthninja) [inline math/modular_division.cpp:28]:
```suggestion
#include <cstdint>
```

**Comment by realstealthninja** [comment]
@Panquesito7 could you have a look please. I think its finally done
