### PR TITLE
fix: Adding documentations, tests, and amending algorithm for gcd_of_n_numbers.cpp

### LINKED ISSUE #2456: [FIX] Pre-existing algorithms do not fit the contribution guidelines
### Detailed description

<h1 align="center">Times change </h1>  
<p align="center">so does the development of algorithms and documentation</p>

Some of the older algorithms existing in this repository do not fit the [contribution guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).

A short list of examples:
 - [Armstrong number](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/armstrong_number.cpp)
 - [binary exponent](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/binary_exponent.cpp)
 - [check prime](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/check_prime.cpp) 
 - [complex numbers](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/complex_numbers.cpp)
 - [square root double](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/sqrt_double.cpp)

### Context

Educating new developers on coding standards is a major priority; As the industry today relies heavily on documentation;
If you were to ask any API developer/user on what the most important part of their development and use it will always be:
 - Code quality
 - documentation

having a fast and performant algorithm is good but whats the point if you cant understand how it works or even why it works.

I think it is in the best interest of us to document our algorithms.

As i consider all algorithms must be:
- beautiful
- understandable
- educational

### Possible implementation

_No response_

### Additional information

Others in the past have made major changes like this to this repository and i think its time for us to do the same. to keep the torch moving.

An homage to [@kvedala] for their part in trying to standardize this repository #805

### PR DESCRIPTION
**Pull request by hollowcrust**
#### Description of Change
Adding documentations, tests, and amending the algorithm to align with current guidelines.

#### Checklist

- [x] Added description of change
- [x] Added tests and example, test must pass
- [x] Added documentation so that the program is self-explanatory and educational - [Doxygen guidelines](https://www.doxygen.nl/manual/docblocks.html)
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 
The current algorithm is not accurate and also does not account for 0 in the array, especially when GCD is undefined if all elements are 0.

### CODE REVIEW

**Comment by realstealthninja** [comment]
please unlink #2456 this does not fix the entirety of that issue. feel free to raise another issue with the name of the algorithm you intend to help update instead.

File: math/gcd_of_n_numbers.cpp [hunk 1]
```diff
@@ -1,41 +1,112 @@
 /**
  * @file
- * @brief This program aims at calculating the GCD of n numbers by division
- * method
+ * @brief This program aims at calculating the GCD of n numbers
  *
+ * @details
+ * The GCD of n numbers can be calculated by
+ * repeatedly calculating the GCDs of pairs of numbers
+ * i.e. gcd(a, b, c) = gcd(gcd(a, b), c)
```
Comment (realstealthninja) [inline math/gcd_of_n_numbers.cpp:8]: feel free to add latex notation of the maths formula to this description

File: math/gcd_of_n_numbers.cpp [hunk 2]
```diff
@@ -1,41 +1,112 @@
...
+ * Euclidean algorithm helps calculate the GCD of each pair of numbers efficiently
+ * 
  * @see gcd_iterative_euclidean.cpp, gcd_recursive_euclidean.cpp
  */
-#include <iostream>
+#include <iostream>  /// for IO operations
+#include <cassert>  /// for assert
```
Comment (realstealthninja) [inline math/gcd_of_n_numbers.cpp:14]: lint this file with clang format

File: math/gcd_of_n_numbers.cpp [hunk 3]
```diff
@@ -1,41 +1,112 @@
...
+ * @brief Self-test implementation
+ * @return void
+ */
+static void test() { 
+    int array_1[1] = {0};
+    int array_2[1] = {1};
+    int array_3[2] = {0, 2};
+    int array_4[3] = {-60, 24, 18};
+    int array_5[4] = {100, -100, -100, 200};
+    int array_6[5] = {0, 0, 0, 0, 0};
```
Comment (realstealthninja) [inline math/gcd_of_n_numbers.cpp:91]: add test cases for large numbers

File: math/gcd_of_n_numbers.cpp [hunk 4]
```diff
@@ -1,41 +1,112 @@
...
+}
+/** 
+ * @brief Main program to compute GCD using division algorithm
+ * @param a Array of integers to compute GCD for
+ * @param n number of integers in the array
+ * @return GCD of the numbers in the array
  */
-int gcd(int *a, int n) {
-    int j = 1;  // to access all elements of the array starting from 1
+int gcd(int a[], size_t n) {
```
Comment (realstealthninja) [inline math/gcd_of_n_numbers.cpp:64]: instead of using a fundamental array
an array from <array>
that is std::array<type>

this lets you remove the size parameter

**Review by realstealthninja — CHANGES_REQUESTED** [review]

**Comment by realstealthninja** [comment]
on a side note is this for hacktober fest so i can label it as such

**Comment by hollowcrust** [comment]
Hi yes this is for Hacktoberfest. Thank you :)

**Review by realstealthninja — CHANGES_REQUESTED** [review]
Lint this file using clang tidy

**Review by realstealthninja — APPROVED** [review]
Lgtm

**Comment by realstealthninja** [comment]
Thank you for you're contribution. A very well written pr. I will leave this up and if there is no objections will merge in a few days. Best wishes for the rest of hacktoberfest ♥️

**Comment by hollowcrust** [comment]
> Thank you for you're contribution. A very well written pr. I will leave this up and if there is no objections will merge in a few days. Best wishes for the rest of hacktoberfest ♥️

Thanks!
